name: Conventional Commit title

on:
  pull_request_target:
    types: [opened, edited, synchronize, reopened]

permissions:
  pull-requests: read

jobs:
  title-check:
    name: title-check
    uses: abijith-suresh/workflows/.github/workflows/conventional-commit-title.yml@0f257b2642d2a010fefe0ff9d03374799d73eb44 # v0.3.0
    permissions:
      pull-requests: read

  pr-title:
    name: Conventional Commit title
    runs-on: ubuntu-latest
    if: always()
    needs: title-check

    steps:
      - name: Verify title check passed
        env:
          TITLE_CHECK_RESULT: ${{ needs.title-check.result }}
        run: |
          if [[ "$TITLE_CHECK_RESULT" != "success" ]]; then
            echo "title-check: $TITLE_CHECK_RESULT"
            exit 1
          fi
